# Site settings
title: Blueprint
email: your-email@domain.com
description: > # this means to ignore newlines until the next element
  Joint effort to make resources and experiences with IATI support for NGOs available to others.
#twitter_username: none
github_username:  rowdydata

#baseurl: "" -- not needed when using 'jekyll serve' to test locally

# Build settings
markdown: redcarpet

collections:
  programmes:
    output: true
  sessions:
    output: true
  exercises:
    output: true
  docs: # cannot use 'documents' because that has special meaning in Jekyll
    output: true
  tools:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "programmes"
    values:
      layout: "programme"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "sessions"
    values:
      layout: "session"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "exercises"
    values:
      layout: "exercise"
