# Site settings
title: Blueprint
email: your-email@domain.com
description: > # this means to ignore newlines until the next element
  Joint effort to make resources and experiences with IATI support for NGOs available to others.
#twitter_username: none
github_username:  rowdydata

baseurl: "http://rowdydata.github.io"

# Build settings
markdown: redcarpet

collections:
  programmes:
    output: true
  packages:
    output: true
  modules:
    output: true
  recipes:
    output: true
  tools:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "programmes"
    values:
      layout: "programme"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "packages"
    values:
      layout: "package"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "modules"
    values:
      layout: "module"
